apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-telemetry-pipeline.fullname" . }}-gateway
  labels:
    {{- include "otel-telemetry-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
  selector:
    {{- include "otel-telemetry-pipeline.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
